name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, xdebug
          coverage: xdebug

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: List installed Composer packages
        run: composer show

      - name: Verify vendor folder
        run: ls -la vendor/phpunit/phpunit

      - name: Give execute permissions to PHPUnit
        run: chmod +x vendor/bin/phpunit

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run PHPUnit Tests
        run: |
          php vendor/bin/phpunit --log-junit reports/test-report.xml tests/IMCTest.php
      - name: Verificar se o relatório foi gerado
        run: ls -la reports

      - name: Publicar resultados dos testes
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: reports/test-report.xml

      - name: Verificar se os testes passaram
        run: |
          if grep -q '<failure' reports/test-report.xml; then
            echo "Testes falharam!"
            exit 1
          else
            echo "Testes passaram com sucesso!😉"
          fi

      - name: Package Project
        run: |
          mkdir build
          rsync -av --exclude='build' --exclude='.git' --exclude='.github' ./ build/
          cd build
          rm -rf tests .git .github
          zip -r ../php-project.zip .
          cd ..