name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, xdebug
          coverage: xdebug

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  phpunit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHPUnit Tests
        run: |
          php vendor/bin/phpunit --log-junit test/report.xml tests/IMCTest.php

      - name: Publicar resultados dos testes
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: test/report.xml

      - name: Verificar se os testes passaram
        run: |
          if grep -q '<failure' test/report.xml; then
            echo "Testes falharam!"
            exit 1
          else
            echo "Testes passaram com sucesso!😉"
          fi

  package-project:
    runs-on: ubuntu-latest
    needs: phpunit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Project
        run: |
          mkdir build
          rsync -av --exclude='build' --exclude='.git' --exclude='.github' ./ build/
          cd build
          rm -rf tests .git .github
          zip -r ../php-project.zip .
          cd ..