name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --log-junit test-report.xml

      - name: Upload test reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-test-report
          path: test-report.xml

  build:
    name: Package Software
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.12.2'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      - name: Build and package the software
        run: |
          # Comando de empacotamento (ajuste conforme necessário)
          tar -czvf my-software-package.tar.gz ./src

      - name: Upload software package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-software-package
          path: my-software-package.tar.gz
